### ISSUE TITLE
Web server: Action queue_bundle_finished_hook timed out for subscriber airdcpp-release-validator

### ISSUE THREAD

**Issue by faltaren** [airdcpp-web/airdcpp-release-validator#14]
I get this error multiple times a day. Restart dosent help. What info do you need from me?

**Comment by maksis** [comment]
Does it happen with all finished bundles? Is the system under high load or is there something else special happening during that? Do you get similar errors with all extensions (you could also try installing the search sites extension)?

**Comment by faltaren** [comment]
Most of them yes. Yes the system is under high load. The share monitor is a problem to. Extensions: Failed to start the extension airdcpp-share-monitor: Failed to initialize the extension log and Web server: Action extension_list_menuitems timed out for subscriber airdcpp-share-monitor. I have the search sites installed. Want me to test it?

**Comment by maksis** [comment]
The timeout for scanning the bundle is one minute, so the system must be really unresponsive if the scan times out. What's causing the high load and are you able to test it with lighter load?

**Comment by faltaren** [comment]
I stopped all downloads and now it scans fine (for now). The disks are under 100% load at times. Its an old intel system. 4 core i5 3,3ghz. ssd systemdisk. Windows 10. 32gb ddr 3 ram.

**Comment by faltaren** [comment]
I finshed one download now. Got this error Extensions: Failed to start the extension airdcpp-share-monitor: Failed to initialize the extension log. File is used by another process. Had to restart the share monitor

**Comment by maksis** [comment]
If the disk load is so high that one minute just simply isn't enough for scanning the bundle, I don't see many other options than increasing the timeout. As the current hook timeouts are hardcoded, that would require changes in the application itself. The best solution might be to add separate timeout settings for each hook type.

**Comment by faltaren** [comment]
I think that would be good.

**Comment by maksis** [comment]
Please try it with the latest beta (Settings -> Miscellaneous -> Update channel). It changes the default timeout from one minute to two minutes. If it's still not enough, you may increase the timeout from the Web UI (Settings -> System -> Advanced -> Bundle downloaded).

**Comment by faltaren** [comment]
[11:08:45] Extensions: Failed to start the extension airdcpp-share-monitor: Failed to initialize the extension log C:\Users\*****\Documents\AirDC++\extensions\airdcpp-share-monitor\logs\output.log: 

Used by another process. 

Im testing the timeouts. 240s now.

**Comment by maksis** [comment]
This fix is only for the release validator, not share monitor. Changing the timeout won't make any difference with share monitoring.

**Comment by faltaren** [comment]
Aha then 2m was enough

Hälsningar

Christopher Fält

________________________________

**Comment by maksis** [comment]
Looks like this can be closed now
