### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by auggy** [airdcpp-web/airdcpp-release-validator#19]
Hey, I tried updating to the lastest version and it's throwing me the error below. 

I'm using ubuntu xenial until next month anyway.
and Node v4.2.6

Is this because of an old os or is my Node instalation wonky? 

/home/mikey/airdcpp-webclient/config/extensions/airdcpp-release-validator/package/dist/main.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t();else if("function"==typeof define&&define.amd)define([],t);else{var n=t();for(var r in n)("object"==typeof exports?exports:e)[r]=n[r]}}(global,(function(){return(()=>{var e={8926:e=>{function t(e,t,n,r,o,i,s){try{var a=e[i](s),c=a.value}catch(e){return void n(e)}a.done?t(c):Promise.resolve(c).then(r,o)}e.exports=function(e){return function(){var n=this,r=arguments;return new Promise((function(o,i){var s=e.apply(n,r);function a(e){t(s,o,i,a,c,"next",e)}function c(e){t(s,o,i,a,c,"throw",e)}a(void 0)}))}}},9713:e=>{e.exports=function(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}},7757:(e,t,n)=>{e.exports=n(5666)},4386:(e,t,n)=>{var r=n(6128),o=n(8739);e.exports=function(e,t){var i=t.extensionN

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by maksis** [comment]
Yes, it's because of an old Node version. You can most likely upgrade to a newer version (such as v14) by following these instructions: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by auggy** [comment]
Thank you. That fixed it.
