### ISSUE TITLE
Show another error message when files are bigger than the value "Don't share files bigger than"

### ISSUE THREAD

**Issue by Sopor** [airdcpp-web/airdcpp-release-validator#29]
When the files are bigger than the value `Don't share files bigger than (0 = disable)` it will show that the files are missing `File listed in the SFV file does not exist on disk`

This is a very confusing message when a file is only too big and not really missing.

So, another message would make it easier for everyone because this will create many questions why the files not will be shared.

**Comment by maksis** [comment]
Try version 1.3.0
